name: Game
main: minigame.plugin.contest.Main
version: 1.0-SNAPSHOT
author: [BumbleBee, Vengeancey]
description: Racing game
commands:
  race:
    description: Main Command

permissions:
  races.join:
    default: true
  races.spectate:
    default: true
  races.*:
    description: All permissions
    default: op
    children:
      races.join: true
      races.spectate: true
      races.addspawn: true
      races.reload: true
      races.wand: true
      races.create: true
      races.setlobby: true
      races.setspectator: true
      races.spawns: true
      races.addspawn: true
      races.delspawn: true
      races.setend: true
      races.setspec: true